// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjUn79ioWGa3mkVym7rQa0B1mwpt5jUjE',
    appId: '1:500063365295:web:5bad564dca4374057f8c5a',
    messagingSenderId: '500063365295',
    projectId: 'auth-26cb4',
    authDomain: 'auth-26cb4.firebaseapp.com',
    databaseURL: 'https://auth-26cb4-default-rtdb.firebaseio.com',
    storageBucket: 'auth-26cb4.appspot.com',
    measurementId: 'G-E53RXJ1B5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTyJDffyo_M2DsYpP5VHFcLPKuxw9x2Kg',
    appId: '1:500063365295:android:d405ac152d62864c7f8c5a',
    messagingSenderId: '500063365295',
    projectId: 'auth-26cb4',
    databaseURL: 'https://auth-26cb4-default-rtdb.firebaseio.com',
    storageBucket: 'auth-26cb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7frr-5NkQ9RxnqFV-EQYSvkSArz1cDs',
    appId: '1:500063365295:ios:38e7c76f91b45d5e7f8c5a',
    messagingSenderId: '500063365295',
    projectId: 'auth-26cb4',
    databaseURL: 'https://auth-26cb4-default-rtdb.firebaseio.com',
    storageBucket: 'auth-26cb4.appspot.com',
    iosClientId: '500063365295-d0bikqnb2nj4279k15dtrcnslikvacs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG7frr-5NkQ9RxnqFV-EQYSvkSArz1cDs',
    appId: '1:500063365295:ios:38e7c76f91b45d5e7f8c5a',
    messagingSenderId: '500063365295',
    projectId: 'auth-26cb4',
    databaseURL: 'https://auth-26cb4-default-rtdb.firebaseio.com',
    storageBucket: 'auth-26cb4.appspot.com',
    iosClientId: '500063365295-d0bikqnb2nj4279k15dtrcnslikvacs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );
}
